/*
Balika Vadhu- Problem
Send Feedback
Anandi and Jagya were getting married again when they have achieved proper age. Dadi
Sa invited Alok Nath to do the kanyadaan and give blessings. Alok Nath has 2 
blessings. Each bessing is in the form of a string consisting of lowercase charaters
(a-z) only. But he can give only one blessing of K length because some priest told
him to do so. Thus he decides to generate a blessing using the other two blessings.
While doing this he wants to ensure that happiness brought into their life by his
blessing is maximum.
The generated blessing is a common subsequence of length K of the two blessings he 
has. Happiness of the blessing he generates is calculated by the sum of ASCII values
of characters in the blessing and he wants the happiness to be maximum. If he is 
not able to generate a common subsequence of length K then the happiness is 0 (zero).
Alok Nath comes to you and asks you to find the maximum happiness that can be 
generated by the two blessings he has.
Input Specification
First line consists of number of test cases t. Each test case consists of two strings
b1 (blessing 1),b2 (blessing 2) and an integer K, each of them in separate lines.
Output Specification
Output consists of t lines each containing an integer denoting the maximum happiness 
value that can be generated by the two blessings.
Constraint
1 <= t <= 50

1 <= length(b1) , length(b2) <= 100 

1 <= K <= 100
Sample Input
2
asdf
asdf
3
anandi
jagya
3
Sample Output
317
0
*/
#include <bits/stdc++.h>
using namespace std;

int recursive(string a, string b, int k, int i, int j, int len, int sum, int dp[][100][100])
{
    if (len == k)
        return sum;
    if (a[i] == '\0' || b[j] == '\0')
        return 0;
    if (dp[i][j][len] >= 0)
        return dp[i][j][len];
    int a1 = 0, a2 = 0;
    if (a[i] == b[j])
        a1 = recursive(a, b, k, i + 1, j + 1, len + 1, sum + a[i], dp);
    a2 = max(recursive(a, b, k, i + 1, j, len, sum, dp), recursive(a, b, k, i, j + 1, len, sum, dp));
    dp[i][j][len] = max(a1, a2);
    return dp[i][j][len];
}
int iter(string a, string b, int k, int dp[][101][101])
{
    struct bless
    {
        int sum;
        int len;
    } dp[100][100][100];
    for (int i = 0; a[i] != '\0'; i++)
    {
        for (int j = 0; b[j] != '\0'; j++)
        {
                }
    }
}
int main()
{
    int t;
    cin >> t;
    while (t--)
    {
        int k;
        string a, b;
        cin >> a >> b >> k;
        int dp[101][101][101];
        memset(dp, -1, sizeof(dp));
        //cout << recursive(a, b, k, 0, 0, 0, 0, dp) << endl;
    }
}
